server:
  port: 8080
spring:
  profiles:
    active: test

---
server:
  port: 8081
spring:
    profiles: dev

#
##对象
##friend:
##  name: hongjun500
##  age: 22
##行内写法
#friend: {name: hongjun500, age: 22}
#
##数组
##list:
##  - people
##  - dog
##  - cart
#list: [people, dog, cart]
#
##demodata:
##  userName: hongjun500
##  age: 22
##  gender: true
##  birth: 2020/05/25
##  map: {k1: '扎格拉玛', k2: '库里莫旗'}
##  list:
##    - '张三'
##    - '李斯'
##  people:
##    name: 'people'
#demodata:
#  user-name:

##    age: 2