spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chapter06_jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hongjun500
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true
#    \u4F7F\u7528InnoDBD\u5F15\u64CE
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
