package com.hongjun.pojo;

import java.util.Date;

public class ItemDO {

    private Integer id;



    private String itemName;


    private String itemType;


    private Long top;

    private Date createTime;


    private Integer sales;

    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_type
     *
     * @return the value of item.item_type
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_type
     *
     * @param itemType the value for item.item_type
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.top
     *
     * @return the value of item.top
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public Long getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.top
     *
     * @param top the value for item.top
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public void setTop(Long top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sales
     *
     * @return the value of item.sales
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sales
     *
     * @param sales the value for item.sales
     *
     * @mbg.generated Wed Jun 10 21:54:25 CST 2020
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }
}